### ISSUE TITLE
Conflict between Crazyradio drivers and other libusb drivers

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyradio-firmware#12]
There has been multiple reports that the Crazyradio drivers will not work if other libusb drivers are installed (like for GoPro or Arduino).

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyradio-firmware/issue/12
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-10-01T10:43:59.319

**Comment by ataffanel** [comment]
Fixed long ago.
