### ISSUE TITLE
Raspberry Pi reset on insertion of Crazyradio PA

### ISSUE THREAD

**Issue by evoggy** [bitcraze/crazyradio-firmware#14]
According to [this thread](http://forum.bitcraze.se/viewtopic.php?f=5&t=1153) the Raspberry Pi resets when the Crazyradio PA is inserted, but not the Crazyradio. Investigate the current consumption at start-up of the Crazyradio PA and if we can effect it in software.

**Comment by ataffanel** [comment]
Cannot reproduce on RaspberryPi 2
