### ISSUE TITLE
Cannot find Crazyradio

### ISSUE THREAD

**Issue by Birdy45** [bitcraze/crazyradio-firmware#47]
Hi, I have followed the instructions on this website: https://www.hackster.io/ataffanel/fixing-crazyradio-usb-bootloader-with-a-raspberry-pi-08796b and seem to get the correct results. When I try to run any of the test code provided I receive a message stating that my Raspberry Pi cannot find the device. I have included the output on my console below to see if that helps, please can anyone help with the issue?

pi@pi-top:~/crazyradio-firmware $ ls
CONTRIBUTING.md examples firmware fix_bootloader lib LICENSE.txt module.json nrfProg README.md tools usbtools
pi@pi-top:~/crazyradio-firmware $ cd crazyradio-firmware
bash: cd: crazyradio-firmware: No such file or directory
pi@pi-top:~/crazyradio-firmware $ cd fix_bootloader_raspi
bash: cd: fix_bootloader_raspi: No such file or directory
pi@pi-top:~/crazyradio-firmware $ cd fix_bootloader
pi@pi-top:~/crazyradio-firmware/fix_bootloader $ python fix_bootloader_raspi.py
Erasing page 0...
Writing 'JL 0x7800' instruction...
Flash content:
02
78
00
Fix written to flash. Disconnect the PROG wire, reconnect Crazyradio
and the bootloader should start!
pi@pi-top:~/crazyradio-firmware/fix_bootloader $ python ../usbtools/launchBootloader.py
Error!, cannot find the CrazyRadio USB dongle!
pi@pi-top:~/crazyradio-firmware/fix_bootloader $ python ../usbtools/nrfbootload.py flash bin/cradio.bin
Error: cannot found the nRF24LU1 bootloader!
pi@pi-top:~/crazyradio-firmware/fix_bootloader $ ls
crazyradio-firmware fix_bootloader_raspi.pyreadme.md
pi@pi-top:~/crazyradio-firmware/fix_bootloader $ cd . .
pi@pi-top:~/crazyradio-firmware/fix_bootloader $ cd ~
pi@pi-top:~ $ ls
3dslash crazyradio-firmware Desktop Documents Downloads Music Pictures Public py-spidev-master python_games Templates Videos
pi@pi-top:~ $ cd crazyradio-firmware
pi@pi-top:~/crazyradio-firmware $ python ../usbtools/nrfbootload.py flash bin/cradio.bin
python: can't open file '../usbtools/nrfbootload.py': [Errno 2] No such file or directory
pi@pi-top:~/crazyradio-firmware $ ls
CONTRIBUTING.md examples firmware fix_bootloader lib LICENSE.txt module.json nrfProg README.md tools usbtools
pi@pi-top:~/crazyradio-firmware $ python usbtools/nrfbootload.py flash bin/cradio.bin
Error: cannot found the nRF24LU1 bootloader!
pi@pi-top:~/crazyradio-firmware $ python ../usbtools/nrfbootload.py flash bin/cradio.bin
python: can't open file '../usbtools/nrfbootload.py': [Errno 2] No such file or directory
pi@pi-top:~/crazyradio-firmware $ ls
CONTRIBUTING.md examples firmware fix_bootloader lib LICENSE.txt module.json nrfProg README.md tools usbtools
pi@pi-top:~/crazyradio-firmware $ cd usbtools
pi@pi-top:~/crazyradio-firmware/usbtools $ python nrfbootload.py flash bin/cradio.bin
Error: cannot found the nRF24LU1 bootloader!
pi@pi-top:~/crazyradio-firmware/usbtools $ python NrfUsbBootload.py flash bin/cradio.bin
python: can't open file 'NrfUsbBootload.py': [Errno 2] No such file or directory
pi@pi-top:~/crazyradio-firmware/usbtools $ python nrfbootload.py flash bin/cradio.bin
Error: cannot found the nRF24LU1 bootloader!
pi@pi-top:~/crazyradio-firmware/usbtools $

**Comment by ataffanel** [comment]
Discussion for this problem happening on the forum: https://forum.bitcraze.io/viewtopic.php?f=8&t=2753
Closing this issue.
