### ISSUE TITLE
Dongle hangs

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyradio-firmware#5]
Sometime the USB dongle will hang and the only way to unlock it is to disconnect it from the PC. This should not happen and, at least, it should be possible to unlock the dongle by sending an USB reset command.

This bug has been mostly observed when boot-loading the Crazyflie and then trying to connect to it.

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyradio-firmware/issue/5
- Originally Reported By: [Arnaud Taffanel](http://bitbucket.org/ataffanel)
- Originally Created At: 2013-05-04T19:03:05.638

**Comment by ataffanel** [comment]
Duplicates #11
