### ISSUE TITLE
you can get an official USB PID for free

### ISSUE THREAD

**Issue by gherlein** [bitcraze/crazyradio-firmware#51]
https://github.com/openmoko/openmoko-usb-oui/blob/master/README.md

OpenMoku is no more but they are allowing their USB license to support open source projects.  If the CrazyRadio had a real PID then we could build a real device driver for it.

I am still fiddling with some derived works from the CrazyRadio and am asking them for a PID, but you guys should definitely get a PID for free while they are available!

**Comment by krichardsson** [comment]
Thanks! We will check it out
