### ISSUE TITLE
Can only connect to CF2 through USB or in bootloader mode

### ISSUE THREAD

**Issue by davidoort** [bitcraze/crazyradio-firmware#57]
I am running the following:
Crazyflie 2.0: I have flashed `firmware-cf2-2020.02.zip` through the `cfclient` GUI.
Crazyradio PA: I have flashed `cradio-pa-0.53.bin` by running the following commands from the root of this repository:
```
cd firmware
make CRPA=1
python ../usbtools/launchBootloader.py 
python ../usbtools/nrfbootload.py flash cradio-pa-0.53.bin
```
after plugging the radio back in the red and green light show up for an instant and then remain off.
`lsusb -d 1915:7777 -v | grep bcdDevice` shows  `bcdDevice            0.53` 
OS Computer: Ubuntu 18.04

When I launch the `cfclient` and press scan I can't find a device unless I connect the CF2 to my computer via the charging port. After trying different combinations of firmware versions on the CF2 and Crazyradio I was able to correctly scan and connect to the CF2 through the radio but I haven't been able to replicate this result since.

This is the output when launching `cfclient`:
```
INFO:cfclient.gui:Disabling STL printouts
INFO:cfclient.utils.input.inputreaders:Input readers: ['linuxjsdev', 'pysdl2']
INFO:cfclient.utils.input.inputreaders:Successfully initialized [linuxjsdev]
INFO:cfclient.utils.input.inputreaders:Could not initialize [pysdl2]: No SDL2 support on Linux
INFO:cfclient.utils.input.inputinterfaces:Found interfaces: ['leapmotion', 'wiimote', 'zmqpull']
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [leapmotion]: Leap Motion library probably not installed (No module named 'leapsdk')
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [wiimote]: Missing cwiid (wiimote) driver No module named 'cwiid'
INFO:cfclient.utils.config:Dist config read from /home/davidoort/crazyflie/crazyflie-clients-python/src/cfclient/configs/config.json
INFO:cfclient.utils.config:Config file read from [/home/davidoort/.config/cfclient/config.json]
INFO:cfclient.utils.input.inputinterfaces:Could not initialize [zmqpull]: ZMQ input disabled in config file
INFO:cfclient.utils.zmq_param:Biding ZMQ for parameters at tcp://*:1213
INFO:cfclient.utils.zmq_led_driver:Biding ZMQ for LED driverat tcp://*:1214
INFO:cfclient.utils.input:Using device blacklist [(VirtualBox|VMware)]
INFO:cfclient.ui.main:Auto reconnect enabled: True
INFO:cflib.crtp.radiodriver:v0.53 dongle with serial N/A found
INFO:cfclient.ui.tabs.QualisysTab:Switching Flight Mode to: FlightModeStates.DISCONNECTED
INFO:cfclient.utils.input:Selected MUX: Normal
INFO:cfclient.ui.main:Role of Microsoft X-Box 360 pad is Device
INFO:cfclient.utils.input.mux:Adding device Microsoft X-Box 360 pad to MUX Normal
INFO:cflib.crtp.serialdriver:Initialized serial driver.
INFO:cflib.drivers.cfusb:Looking for devices....
INFO:cflib.crtp.prrtdriver:Initialized PRRT driver.
```

**Comment by krichardsson** [comment]
Your Crazyflie might be on a different address.

In the python client:
1. Connect your Crazyflie with USB
1. Go to the Connect/Configure 2.X menu 
1. Check which address it is set to

You can either enter this address in the client (Address field) and th CF should be found when scanning, or you can change the address in the Crazyflie to the the default address 0xE7E7E7E7E7 (you must restart the CF for the new address to be active)

**Comment by davidoort** [comment]
This is what I see when I open the Python Client GUI
![image](https://user-images.githubusercontent.com/21220927/77641606-98d52000-6f5c-11ea-8dc7-f4c625a9b65e.png)
When I hover over Connect, the Configure 2.X option is not clickable. What could be causing this?

**Comment by krichardsson** [comment]
Ok, you need to click the "Connect" button first to connect to the Crazyflie (it will connect via USB). After that the Connect/Configure 2.X menu should be enabled

**Comment by davidoort** [comment]
Great! I connected through USB, changed the address from what it was set (0xE7E7E7E735) to 0xE7E7E7E7E7 and after writing and restarting the CF, I was able to scan the CF through the radio. Thank you so much!
