### ISSUE TITLE
Not able to launch bootoloader when Firmware built with SDCC 3.1

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyradio-firmware#6]
When the radio dongle is built with SDCC 3.1 (default version in Ubuntu 13.4, this also affects the bitcraze virtual machine) the resulting firmware cannot launch the bootloader using the normal sequence.

This bug does not appear with SDCC 3.2

---------------------------------------
- Bitbucket: https://bitbucket.org/bitcraze/crazyradio-firmware/issue/6
- Originally Reported By: [Arnaud Taffanel](http://bitbucket.org/ataffanel)
- Originally Created At: 2013-05-14T09:18:28.120

**Comment by ataffanel** [comment]
Already fixed
