### ISSUE TITLE
flashing issue 

### ISSUE THREAD

**Issue by antbono** [bitcraze/crazyradio-firmware#62]
Hello everyone! 
I have just followed the instructions to compile the firmware on a freshly installed ubuntu 22.04 (my default python version is 3.8.10). I can start the bootlader but when I try to flash, I obtain the following error. 

![error](https://user-images.githubusercontent.com/7023471/207880830-ea32f463-35ec-4b3b-bc47-bc7623c81c9d.png)

Please consider that I successfully use the dongle with the crazyflie python client for ubuntu and I have the pyusb library installed.

Thank you for your attention!

This is the result of the building

![build](https://user-images.githubusercontent.com/7023471/207883099-0029133f-960d-4ef4-a396-82ff81b2d145.png)

**Comment by kripton** [comment]
Hi @antbono : Do you have the package "pyusb" installed? https://pyusb.github.io/pyusb/ https://pypi.org/project/pyusb/

If not, try installing it and try again

**Comment by antbono** [comment]
Hi @kripton!

Yes I have installed that library

![pyusb](https://user-images.githubusercontent.com/7023471/207883265-c65b20a1-8c3c-45ac-801c-f13e296879b1.png)

**Comment by antbono** [comment]
Sorry I missed 'sudo' in the pip install command...

**Comment by krichardsson** [comment]
As far as I understand this issue has been fixed and I will close this issue. Please reopen if there is still a problem!
