### ISSUE TITLE
How to run crazyradio-firmware on different hardware

### ISSUE THREAD

**Issue by allegorywrite** [bitcraze/crazyradio-firmware#64]
Hi, I'm not sure if crazyradio PA is under FCC compliant, so I would like to use another product with firmware instead of crazyradio PA or 2.0.
What configurations are considered compatible with crazyradio firmware? Or do you think such an attempt will not work very well?

**Comment by ataffanel** [comment]
Hi,
Communication with Crazyflie can be achieve with any Nordic semiconductor chip that supports the proprietary Mordic radio mode. It may also work with other 2.4GHz radio given it can achieve the same modulation parameters and packet structure but this is not something we have ever tried.

Getting the firmware to run on other hardware is likely possible but this is not something we have worked with so this is not something we know much about.
