### ISSUE TITLE
Input/Output Error

### ISSUE THREAD

**Issue by JCdeception** [bitcraze/crazyradio-firmware#67]
python2 ../usbtools/launchBootloader.py
Launch bootloader Traceback (most recent call last):
  File "../usbtools/launchBootloader.py", line 95, in <module>
    sys.exit(launchBootloader(True))
  File "../usbtools/launchBootloader.py", line 61, in launchBootloader
    handle.controlMsg(0x40, 0xFF, (), value=0, index=0, timeout=5000)
  File "/usr/lib/python2.7/dist-packages/usb/legacy.py", line 211, in controlMsg
    timeout = timeout)
  File "/usr/lib/python2.7/dist-packages/usb/core.py", line 1043, in ctrl_transfer
    self.__get_timeout(timeout))
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer
    timeout))
  File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check
    raise USBError(_strerror(ret), ret, _libusb_errno[ret])
usb.core.USBError: [Errno 5] Input/Output Error
any help on fixing this issue

**Comment by ataffanel** [comment]
We will need a little bit more context and information in order to be able to help:
 - What OS are you running, do you have access to the USB device (ie. have you installed the udev-rules needed for your user to access USB devices).
 - What version of the Crazyradio are you using and what firmware is it running, this script only works on a Crazyradio PA running an official firmware from this repos
 - Is your Crazyradio working? Why are you trying to run this script?

Any other information or context will help us help you.

**Comment by HoAd-sc** [comment]
I'm also having the same issue, I'm inside kali, and while performing the launchBootloader.py, I use lsusb to discover the 1915:7777 Crazyradio device

**Comment by HoAd-sc** [comment]
> python2 ../usbtools/launchBootloader.py Launch bootloader Traceback (most recent call last): File "../usbtools/launchBootloader.py", line 95, in sys.exit(launchBootloader(True)) File "../usbtools/launchBootloader.py", line 61, in launchBootloader handle.controlMsg(0x40, 0xFF, (), value=0, index=0, timeout=5000) File "/usr/lib/python2.7/dist-packages/usb/legacy.py", line 211, in controlMsg timeout = timeout) File "/usr/lib/python2.7/dist-packages/usb/core.py", line 1043, in ctrl_transfer self.__get_timeout(timeout)) File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 883, in ctrl_transfer timeout)) File "/usr/lib/python2.7/dist-packages/usb/backend/libusb1.py", line 595, in _check raise USBError(_strerror(ret), ret, _libusb_errno[ret]) usb.core.USBError: [Errno 5] Input/Output Error any help on fixing this issue

Solved it?

**Comment by HoAd-sc** [comment]
Seems like I'm using Crazyradio 2.0? What's the solution?

**Comment by gemenerik** [comment]
> I'm also having the same issue, I'm inside kali, and while performing the launchBootloader.py

Do you get exactly the same error? If so, can you give some context like @ataffanel suggested? 

> I use lsusb to discover the 1915:7777 Crazyradio device

The device showing in lsusb does not imply _access_ to the USB device.

**Comment by HoAd-sc** [comment]
I found the reason: I am using crazyradio2, and this project is crazyradio's

**Comment by ataffanel** [comment]
Yes this is the reason. Crazyradio 2 is very different and is using a proper safe bootloader and the same debug port than the Crazyflie. So if you want to start working with the Crazyradio2 firmware, you can find our Zephyr-based firmware there: https://github.com/bitcraze/crazyradio2-firmware

Please note that Crazyradio 2 already works with Crazyswarm (2) out of the box so there is not need to flash it for that reason.
