### ISSUE TITLE
Dongle returns garbage back when doing fw scan

### ISSUE THREAD

**Issue by bitcraze-issue-importer** [bitcraze/crazyradio-firmware#9]
When doing a firmware accelerated scan on version 0.51 garbage is returned from the dongle (see below). This has so far only been reproduced on Arch Linux running kernel 3.9.4-1 and USB3. The same dongle on Linux Mint (kernel 3.2.0-41) and USB2 doesn't give this error.

The fact that a Crazyflie should or should't be detected when doing the scan doesn't change this behavior.

Below is a printout of the tuples created for each call to __get_vendor_setup(self.handle, SCANN_CHANNELS, 0, 0, 64)_

```
#!

INFO:cflib.crtp.radiodriver:v0.51 dongle with serial N/A found
tuple len 64
(64, 249, 120, 165, 0, 136, 255, 255, 192, 244, 120, 165, 0, 136, 255, 255, 208, 244, 120, 165, 0, 136, 255, 255, 208, 244, 120, 165, 0, 136, 255, 255, 0, 179, 52, 119, 0, 136, 255, 255, 224, 139, 2, 79, 1, 136, 255, 255, 176, 187, 164, 31, 0, 136, 255, 255, 208, 187, 164, 31, 0, 136, 255, 255)
tuple len 64
(128, 204, 147, 56, 1, 136, 255, 255, 131, 204, 4, 0, 208, 24, 1, 0, 125, 37, 156, 0, 1, 0, 0, 0, 0, 1, 16, 0, 0, 0, 173, 222, 0, 2, 32, 0, 0, 0, 173, 222, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 16, 0, 0, 0, 173, 222, 0, 2, 32, 0, 0, 0, 173, 222)
tuple len 64
(64, 249, 120, 165, 0, 136, 255, 255, 0, 249, 120, 165, 0, 136, 255, 255, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 152, 154, 111, 61, 1, 136, 255, 255, 24, 68, 14, 66, 1, 136, 255, 255, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0)
```

Reported in the forums: http://forum.bitcraze.se/viewtopic.php?f=8&t=303

---
- Bitbucket: https://bitbucket.org/bitcraze/crazyradio-firmware/issue/9
- Originally Reported By: [Marcus Eliasson](http://bitbucket.org/MackeE)
- Originally Created At: 2013-06-04T07:21:29.792

**Comment by ataffanel** [comment]
I have isolated the location of the problem. With a Nexus-5 if the scann reports no data, so if this control read only returns a zero length packet (https://github.com/bitcraze/crazyradio-firmware/blob/master/firmware/src/main.c#L278), the Nexus 5 will receive buffer full of garbage. If the packet is anything else than 0 (like 1), things works fine.

**Comment by ataffanel** [comment]
After further investigation, no data is transfered from the dongle so this looks like a linux usb bug. I cannot reproduce the bug with modern version of Linux.

The bug is that when the device returns an empty data buffer to the control read, the host reports a full buffer instead. In that case a buffer of 64 bytes is asked for, and so a buffer on 64 bytes is reported. 

A workaround is to ignore results of 64 bytes since this is anyway not possible, the maximum number of scann result is 63: https://github.com/bitcraze/crazyradio-firmware/blob/master/firmware/src/main.c#L60-L62

**Comment by ataffanel** [comment]
Implemented the workaround in the python lib from this repos and documented the bug in the usb protocol documentation (https://wiki.bitcraze.io/doc:crazyradio:usb:index#channels_scanning). This (finally) closes this ticket.
